---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# tabswift

<!-- badges: start -->
<!-- badges: end -->

The goal of tabswift is to provide R bindings to TabSwift, a row-wise in-context-learning tabular foundation model. 

For more information, please visit the official repository: https://github.com/LAMDA-Tabular/TabSwift

## Installation

You can install the development version of tabswift like so:

```r
pak::pak("frankiethull/tabswift")
```

## Example

```{r example}
library(tabswift)
library(rsample)

corn_data <- maize::corn_data

corn_splits <- initial_validation_split(corn_data)
train <- training(corn_splits)
validate <- validation(corn_splits)
test <- testing(corn_splits)
```

### Classification

```{r, eval=FALSE}
fit_cls <- swift_fit(
  train |> dplyr::select(-type), train$type,
  n_estimators = 5L,
  device = "cpu"
)

class_preds <- swift_predict(fit_cls, test |> dplyr::select(-type))
```


### Regression

```{r, eval=FALSE}
fit_reg <- swift_fit(
  train |> dplyr::select(-height, -type), train$height, 
  problem_type = "regression", 
  device = "cpu"
)

preds <- swift_predict(fit_reg, test |> dplyr::select(-height, -type))
```